algoritmo "semnome

var
  valor1,valor2,valor3,valor4,valor5,valor_final:real
  
inicio
  escreval("qual o primeiro valor?")
  leia(valor1)
  escreval("qual o segundo valor?")
  leia(valor2)
  escreval("qual o terceiro valor?")
  leia(valor3)
  escreval("qual o quarto valor?")
  leia(valor4)
  escreval("qual o quinto valor?")
  leia(valor5)
  
  valor_final<-valor1+valor2+valor3+valor4+valor5
  
  escreval
  escreval("o valor final é:",valor_final)
fimalgoritmo
