algoritmo "semnome"

var
  valor1,valor2,valor3,valor4,valor5,media:real
inicio
  escreval("Qual o primeiro valor?")
  leia(valor1)
  escreval("Qual o segundo valor?")
  leia(valor2)
  escreval("Qual o terceiro valor?")
  leia(valor3)
  escreval("Qual o quarto valor?")
  leia(valor4)
  escreval("Qual o quinto valor?")
  leia(valor5)
  
  
  media<-(valor1*2+valor2*4+valor3*2+valor4*5+valor5*3)/16
  
  escreval
  escreval("A media é:",media)
fimalgoritmo
