algoritmo "semnome"

var

Caracteres:inteiro
Palavra:caracter

inicio

escreval("Me de uma palavra que tenha no minimo 4 e no maximo 30 caracteres:")
leia(Palavra)

Caracteres<-compr(Palavra)

enquanto (Caracteres<4) ou (Caracteres>30) faca

   escreval("Me de uma palavra que tenha no minimo 4 e no maximo 30 caracteres:")
   leia(Palavra)

   Caracteres<-compr(Palavra)

fimenquanto


escreval
escreval("A palavra tem ", Caracteres," caracteres")


fimalgoritmo
