algoritmo "semnome"

var

procedimento gerar

var

inicio

para i de 1 ate 20 faca

     repita

           cont <- 0
     
           vet[i] <- randi(100)+1
           
           se (vet[i] % 2 = 0) entao

              cont <-1
              
           fimse
           
     ate cont <- 0
     
fimpara

fimprocedimento

//------------------------------------------------------------------------------

inicio

fimalgoritmo
