algoritmo "semnome"

var

n:vetor[1..4,1..3] de inteiro
i,x:inteiro

inicio

para i de 1 ate 4 faca

     para x de 1 ate 3 faca
     
          escreval("Me fale o", i, "," ,x ,"º número: ")
          leia(n[i,x])
          
     fimpara
     
fimpara

i<-0

x<-0

limpatela

para i de 1 ate 4 faca

     para x de 1 ate 3 faca
     
          escreva(n[i,x]," ")
          
     fimpara

     escreval
     
fimpara




fimalgoritmo
